version: "3.1"

services:
  api:
    container_name: qlFLASK
    build: ./api
    ports:
      - 8000:8000
    environment:
      JWT_SECRET: insert_jwt_secret_here
    depends_on:
      - redis
  
  redis:
    container_name: qlREDIS
    image: redis:6.2.0-alpine
    volumes:
      - redis_database:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 10

volumes:
  redis_database: